### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by flxai** [nschloe/xhub#81]
I don't know if this is feasible, but is support for Firefox planned?

**Comment by nschloe** [comment]
Depends on when Mozilla will implement Manifest v3, see [here](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/).

**Comment by mahyarmirrashed** [comment]
It is very unlikely that that will ever happen. See the privacy problems with Manifest v3 [here](https://www.eff.org/deeplinks/2021/12/chrome-users-beware-manifest-v3-deceitful-and-threatening).

**Comment by tobiasdiez** [comment]
Would it maybe be an idea to convert the manifest file back to v2 for firefox (keeping v3 for chrome)? It looks like you don't use anything fancy of v3 (in particular the background worker should work as a normal background script on first glance).

**Comment by mahyarmirrashed** [comment]
> Would it maybe be an idea to convert the manifest file back to v2 for firefox (keeping v3 for chrome)? It looks like you don't use anything fancy of v3 (in particular the background worker should work as a normal background script on first glance).

I might fork the project to get that done. Would you be interested in contributing?

**Comment by nschloe** [comment]
> Would it maybe be an idea to convert the manifest file back to v2 for firefox (keeping v3 for chrome)?

I won't maintain two separate projects, and going back to Manifest v2 isn't an option since [that will be removed from Chrome entirely next year](https://developer.chrome.com/blog/mv2-transition/).

> I might fork the project to get that done. Would you be interested in contributing?

Feel free to fork, I can link the project in the readme.

**Comment by tobiasdiez** [comment]
I was hoping it would be enough to add a `manifest-firefox.json` (that is essentially a backport of the current manifest to v2) and then use webpack with a browser switch (or web-ext) to bundle the extension for firefox using this manifest. So no full fork necessary. But that of course relies on the rest of the code to be compatible with v2.

**Comment by nschloe** [comment]
I see, yeah, that'd be doable. Can you check if it's compatible?

**Comment by tobiasdiez** [comment]
I don't have time right now to actively work on this but will happily review code and answer questions that come up.
